### ISSUE TITLE
Percentage at the left of a slider

### ISSUE THREAD

**Issue by autopear** [DHowett/preferenceloader#1]
The percentage is shown at the left hand side of a slider instead of in the black area at the right hand side.

**Comment by DHowett** [comment]
This is a Preferences.framework bug and cannot be fixed in
PreferenceLoader. PreferenceLoader just loads bundles.

**Comment by autopear** [comment]
Can you hook into the framework and fix it?

On Fri, Feb 10, 2012 at 3:24 PM, Dustin L. Howett <
reply@reply.github.com

**Comment by DHowett** [comment]
Enhancement tracked in #5.
