### ISSUE TITLE
iOS 8.3 Support

### ISSUE THREAD

**Issue by tijmenvn** [DHowett/preferenceloader#10]
As you may or may not have noticed. This tweak is broken with the new 8.3 update. Just doesn't show up in settings at all. Have already 3 apps that make use of this tweak. So it's not the lack of support on their side

**Comment by DHowett** [comment]
Has Substrate even been updated for 8.3 yet? Sources tell me it hasn't, so
no tweaks (this one included) will work.

**Comment by DHowett** [comment]
Closing this issue. If there is still an issue after Substrate has been updated, please create create a new one.

**Comment by FlashBitCode** [comment]
Not working for iOS 8.3 !!!

**Comment by tijmenvn** [comment]
Read the comments first, substrate needs to be updated. 80% of the tweaks on iOS 8.3 aren't working as of now

**Comment by FlashBitCode** [comment]
For IOS 7 you use %hook PrefsListController in iOS 8.3 use header PSRootController ;)

**Comment by FlashBitCode** [comment]
Saurik has updated two times Cydia Installer

**Comment by tijmenvn** [comment]
Cydia installer is not the same as the Cydia substrate. Just be patient for a Cydia substrate update. And if this tweak doesn't work after that update. Then you may open a new issue. For now, just wait for the update

**Comment by FlashBitCode** [comment]
of course I know that the substrate is divevrso but if the installer has released this will soon release an updated substrate! But headers preferences have changed in ios 8.3

**Comment by DHowett** [comment]
PSRootController is the parent class for every preferences pane on the system. I very much doubt that it would be the correct thing to modify.

I'm locking this issue until Substrate is updated.
