### ISSUE TITLE
PreferenceLoader is broken on iOS 4.2.1 - Blank pages in settings

### ISSUE THREAD

**Issue by pizzadude** [DHowett/preferenceloader#2]
Apps that use PreferenceLoader are now broken  on older devices running firmwares such as iOS 4.2.1, like the iPod Touch 2g, because the settings pages for those apps are blank. I suspect this has something to do with a recent update to PreferenceLoader. Please fix.

**Comment by pizzadude** [comment]
Here is a screenshot of this issue.
![photo](https://f.cloud.github.com/assets/1454420/56630/f185fe1e-5b22-11e2-829c-94a870d55f1b.PNG)

**Comment by DHowett** [comment]
Hi! Could you include a syslog snippet from around the time of the issue?
Install `syslogd to /var/log/syslog` in Cydia, reboot your device, and then launch Settings and view a broken preferences panel.

Afterwards, run `grep Preferences /var/log/syslog` to clip the log to only the relevant portions. Paste it here in a code block.

**Comment by pizzadude** [comment]
Thanks for replying. 
Here's the log of me trying to view the settings page for Color Keyboard:

`Jan 10 14:15:07 localhost configd[27]: adding  com.apple.SystemConfiguration.PreferencesMonitor
Jan 10 14:15:10 localhost configd[27]: WiFi:[379538110.125848]: WiFi Preferences is up to date
Jan 10 14:15:22 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:15:33 Aaron-Es-iPod configd[27]: CaptiveNetworkSupport:CNSPreferencesBuildSSIDLookup:278 ssidLookup:
Jan 10 14:16:02 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:16:11 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:16:15 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:16:20 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Installing: com.apple.Preferences [Preferences] (550.52)
Jan 10 14:16:20 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ActionMenu.dylib
Jan 10 14:16:20 Aaron-Es-iPod Preferences[159]: ActionMenu enabled
Jan 10 14:16:20 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Activator.dylib
Jan 10 14:16:20 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: message not found [PrefsListController lazyLoadBundle:]
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Backgrounder.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib, 9): no suitable image found.  Did find:\n /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib: incompatible cpu-subtype: 0x00000009 in /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib\n  /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib: stat() failed with errno=0
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib, 9): Symbol not found: _ABCGetPersonCountInSourceShowingLinks\n  Referenced from: /Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib\n  Expected in: /System/Library/Frameworks/AddressBook.framework/AddressBook
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/IconSupport.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/PreferenceLoader.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ResetAllKiller.dylib
Jan 10 14:16:21 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x198][159]: dyld: F_ADDFILESIGS failed for /
Jan 10 14:16:21 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x198][159]: Library/MobileSubstrate/DynamicL
Jan 10 14:16:21 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x198][159]: ibraries/ResetAllKiller.dylib wi
Jan 10 14:16:21 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x198][159]: th errno=22
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ShowCase.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Springtomize.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/SwipeBack.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/WinterBoard.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector checkoutAccessoryImageForIcon:location:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector checkoutBadgeImageForText:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector generateIconImage:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: message not found [UIImage defaultDesktopImage]
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector _defaultDesktopImage
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector resetCurrentImageToWallpaper
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector init
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector setIconImageAlpha:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector setIconLabelAlpha:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector initWithDefaultSize
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector setAlpha:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector updateNumberOfRootIconLists
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector layoutSubviews
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector renderedSizeOfNode:constrainedToWidth:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector initWithFrame:delegate:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector _canUseLayerBackedBalloon
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector layoutSubviews
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector addBalloonView:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector setBackgroundColor:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector initWithStyle:reuseIdentifier:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector setSeparatorStyle:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector initWithFrame:style:
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: nil class argument for selector loadView
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/libstatusbar.dylib
Jan 10 14:16:21 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/manualcorrect.dylib
Jan 10 14:16:22 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Warning: message not found [UIKeyboardImpl acceptWord:firstDelete:addString:]
Jan 10 14:16:22 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib
Jan 10 14:16:22 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib, 9): Symbol not found: _OB˙ﬁ^L¿\n  Referenced from: /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib\n  Expected in: /System/Library/Frameworks/UIKit.framework/UIKit
Jan 10 14:16:22 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x198][159]: dyld: F_ADDFILESIGS failed for /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib with errno=22
Jan 10 14:16:22 Aaron-Es-iPod /Applications/Preferences.app/Preferences[159]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/sandcastleclient.dylib
Jan 10 14:16:22 Aaron-Es-iPod Preferences[159]: Could not find mapped image Silver_CARRIER_AARONE.png
Jan 10 14:16:25 Aaron-Es-iPod Preferences[159]: Could not find mapped image Silver_Backgrounder_Native.png
Jan 10 14:16:25 Aaron-Es-iPod Preferences[159]: Could not find mapped image ColorOnGrayShadow_Backgrounder_Native.png
Jan 10 14:16:43 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:16:46 Aaron-Es-iPod Preferences[159]: Error loading /System/Library/PreferenceBundles/ColorKeyboardSettings.bundle/ColorKeyboardSettings:  dlopen(/System/Library/PreferenceBundles/ColorKeyboardSettings.bundle/ColorKeyboardSettings, 265): no suitable image found.  Did find:\n   /System/Library/PreferenceBundles/ColorKeyboardSettings.bundle/ColorKeyboardSettings: incompatible cpu-subtype: 0x00000009 in /System/Library/PreferenceBundles/ColorKeyboardSettings.bundle/ColorKeyboardSettings\n    /System/Library/PreferenceBundles/ColorKeyboardSettings.bundle/ColorKeyboardSettings: stat() failed with errno=0
Jan 10 14:16:53 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:36:18 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:36:18 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 14:36:22 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}`

**Comment by DHowett** [comment]
It appears that in this instance, ColorKeyboard, the author has paid no mind to old devices with `armv6` processors. The preferencebundle and library for ColorKeyboard fail to load due to the different processor.

I imagine that to be the issue with many preferencebundles updated after 6.0 came out - unfortunately, that's an issue with said preferencebundle; PreferenceLoader cannot work around it.

**Comment by pizzadude** [comment]
Ok, that's a shame. I assume it's the same with Barrel?

`Jan 10 15:20:41 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:20:42 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:20:47 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:21:02 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:21:02 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:21:08 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:21:10 Aaron-Es-iPod com.apple.launchd[1] (UIKitApplication:com.apple.Preferences[0x198][159]): (UIKitApplication:com.apple.Preferences[0x198]) Exited: Killed
Jan 10 15:22:03 localhost configd[27]: adding  com.apple.SystemConfiguration.PreferencesMonitor
Jan 10 15:22:06 localhost configd[27]: WiFi:[379542126.462205]: WiFi Preferences is up to date
Jan 10 15:22:20 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:22:32 Aaron-Es-iPod configd[27]: CaptiveNetworkSupport:CNSPreferencesBuildSSIDLookup:278 ssidLookup:
Jan 10 15:22:55 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:23:06 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:23:11 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:23:24 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Installing: com.apple.Preferences [Preferences] (550.52)
Jan 10 15:23:24 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ActionMenu.dylib
Jan 10 15:23:24 Aaron-Es-iPod Preferences[160]: ActionMenu enabled
Jan 10 15:23:24 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Activator.dylib
Jan 10 15:23:24 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: message not found [PrefsListController lazyLoadBundle:]
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Backgrounder.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib, 9): no suitable image found.  Did find:\n /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib: incompatible cpu-subtype: 0x00000009 in /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib\n  /Library/MobileSubstrate/DynamicLibraries/ColorKeyboard.dylib: stat() failed with errno=0
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib, 9): Symbol not found: _ABCGetPersonCountInSourceShowingLinks\n  Referenced from: /Library/MobileSubstrate/DynamicLibraries/ContactPrivacy.dylib\n  Expected in: /System/Library/Frameworks/AddressBook.framework/AddressBook
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/IconSupport.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/PreferenceLoader.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ResetAllKiller.dylib
Jan 10 15:23:25 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x5a36][160]: dyld: F_ADDFILESIGS failed for /Library/MobileSubstrate/DynamicLibraries/ResetAllKiller.dylib with errno=22
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/ShowCase.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Springtomize.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/SwipeBack.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/WinterBoard.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector checkoutAccessoryImageForIcon:location:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector checkoutBadgeImageForText:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector generateIconImage:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: message not found [UIImage defaultDesktopImage]
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector _defaultDesktopImage
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector resetCurrentImageToWallpaper
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector init
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector setIconImageAlpha:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector setIconLabelAlpha:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector initWithDefaultSize
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector setAlpha:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector updateNumberOfRootIconLists
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector layoutSubviews
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector renderedSizeOfNode:constrainedToWidth:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector initWithFrame:delegate:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector _canUseLayerBackedBalloon
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector layoutSubviews
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector addBalloonView:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector setBackgroundColor:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector initWithStyle:reuseIdentifier:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector setSeparatorStyle:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector initWithFrame:style:
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: nil class argument for selector loadView
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/libstatusbar.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/manualcorrect.dylib
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Warning: message not found [UIKeyboardImpl acceptWord:firstDelete:addString:]
Jan 10 15:23:25 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib
Jan 10 15:23:26 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Error: dlopen(/Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib, 9): Symbol not found: _OB˙ﬁ^L¿\n  Referenced from: /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib\n  Expected in: /System/Library/Frameworks/UIKit.framework/UIKit
Jan 10 15:23:26 Aaron-Es-iPod UIKitApplication:com.apple.Preferences[0x5a36][160]: dyld: F_ADDFILESIGS failed for /Library/MobileSubstrate/DynamicLibraries/qStatusHelper.dylib with errno=22
Jan 10 15:23:26 Aaron-Es-iPod /Applications/Preferences.app/Preferences[160]: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/sandcastleclient.dylib
Jan 10 15:23:26 Aaron-Es-iPod Preferences[160]: Could not find mapped image Silver_CARRIER_AARONE.png
Jan 10 15:23:29 Aaron-Es-iPod Preferences[160]: Could not find mapped image Silver_Backgrounder_Native.png
Jan 10 15:23:29 Aaron-Es-iPod Preferences[160]: Could not find mapped image ColorOnGrayShadow_Backgrounder_Native.png
Jan 10 15:23:33 Aaron-Es-iPod Preferences[160]: Error loading /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs:  dlopen(/Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs, 265): no suitable image found.  Did find:\n /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs: incompatible cpu-subtype: 0x00000009 in /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs\n  /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs: stat() failed with errno=0
Jan 10 15:23:42 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:24:49 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:24:49 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}
Jan 10 15:24:53 Aaron-Es-iPod SpringBoard[29]: LW: Loading weather prefs: /var/mobile/Library/Preferences/com.apple.weather.plist, {\n}`

**Comment by DHowett** [comment]
Indeed. :( The relevant line is: `Jan 10 15:23:33 Aaron-Es-iPod Preferences[160]: Error loading /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs: dlopen(/Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs, 265): no suitable image found. Did find:\n /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs: incompatible cpu-subtype: 0x00000009 in /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs\n /Library/PreferenceBundles/threedeeprefs.bundle/threedeeprefs: stat() failed with errno=0`

`incompatible cpu-subtype: 0x00000009` :(

**Comment by pizzadude** [comment]
Ok, well thanks for your help anyways. :)

**Comment by DHowett** [comment]
Indeed. Sorry to bear bad news!
