### ISSUE TITLE
Preference Loader ios7

### ISSUE THREAD

**Issue by aboutawm** [DHowett/preferenceloader#8]
Hi there,
I recently updated my iPad to iOS 7.0.4 and jail broke it. Unfortunately, I can't see the apps settings in the settings menu. I searched about a solution and i found that I have to reinstall the preference loader. I did the reinstall but the problem persists.

Can you help?

Thank you in advance

Aboutawm

**Comment by DHowett** [comment]
Additional research would have shown that MobileSubstrate does not work
properly on iOS 7 right now. This is not a preferenceloader bug.
